### ISSUE TITLE
Lista tareas backend

### ISSUE THREAD

**Issue by mariooc04** [UNIZAR-30226-2023-12/Backend#17]
***Autor:*** Mario Ortega y Álvaro López
***Fecha de creación:*** 22-03-2023
***Fecha estimada de finalización:***

# Descripción
Apuntadas distintas tareas a realizar entre Mario y Álvaro

# Tareas

- [x] RFU-4: Faltan en el django las funciones de la API: SetSongLista, SetMultipleSongsLista, GetListasUsr (mínimo para cumplir el requisito)
- [x] Añadir en los daos para tener un id artificial incremental (entre los dos)
- [x] DAO notificaciones -> Álvaro
- [x] Módulo control de calidades (Mario)
- [x] Módulo control audios (Mario)
- [x] Módulo audios -> hacer funciones básicas que usen las funciones de los daos y conforme se vayan necesitando más para cumplir con los requisitos ir implementando (Mario)
- [x] Módulo usuarios hacer funciones básicas que usen las funciones de los daos y conforme se vayan necesitando más para cumplir con los requisitos ir implementando (Álvaro)

**Comment by mariooc04** [comment]
Están creados los módulos referentes a audios con funcionalidad básica.
En la view setSong falta añadir la comprobación de que el usuario que intenta realizar la petición de añadir sea válido

**Comment by CristinaMarzo** [comment]
He añadido una nueva tarea para poder satisfacer el RFU-4. También hay que definir una nueva función en la API (lo voy a poner como un issue diferente).
