### ISSUE TITLE
Daos con mapas como parámetro

### ISSUE THREAD

**Issue by hsunekichi** [UNIZAR-30226-2023-12/Backend#6]
***Autor:***
Hugo Mateo
***Fecha de creación:***
4/3/23
***Fecha estimada de finalización***

# Descripción

Modificar los Daos para que usen mapas como parámetros

**Comment by mariooc04** [comment]
Modificadas funciones de crear canciones, podcasts, playlists y carpetas para funcionar con diccionarios.
Para crear carpetas y playlist hacen falta dos como parámetros, uno con los atributos de la playlist/carpeta y otro con los ids de los audios/playlist asociados a dicha playlist/carpeta
